import {
  Trophy, Shield, PiggyBank, TrendingUp, TrendingDown, Zap, Crosshair,
  Smartphone, Handshake, DollarSign, Microscope, Monitor, BarChart3,
  ClipboardList, MessageCircle, PenTool, RefreshCw, Search, Ban,
  Lightbulb, AlertTriangle, Laptop, BookOpen, Globe, Rocket, Briefcase,
  Scale, Sun, Waves, Compass, Brain, Gamepad2, Star, Lock, KeyRound,
  Mail, Landmark, Bitcoin, Banknote, FileText, Sprout, Wallet, Gift,
  PartyPopper, Wrench, Phone, GraduationCap, CreditCard, Circle,
  Building2, Package, Dice6, Award, Dog, Droplets, Coins, Palmtree,
  Satellite, Settings, Factory, Gauge, Flame, Infinity, Gem, ArrowRight,
  ChevronRight, ChevronDown, ChevronUp, Check, X, Menu, HelpCircle,
  ExternalLink, CircleCheck, CircleX, Calendar, Newspaper, Bot,
  MonitorSmartphone, Shuffle, FolderOpen, ArrowRightLeft, MapPin,
  FastForward, CheckCircle2, Hash, Users, Timer, Linkedin,
  // New icons for ranking system
  ChartCandlestick, ChartLine, ChartArea, ChartBar, ChartNoAxesCombined,
  ShieldCheck, ShieldAlert, BadgeCheck, BadgePercent, BadgeDollarSign,
  CircleDollarSign, CircleOff, HandCoins, Vault, Crown, Sparkles,
  Copy, Signal, Server, Layers, Grid3x3, Target, Activity,
  Cpu, Code, Apple, Moon, Umbrella, Headphones, ScanLine,
  Receipt, Fuel, Wheat, Hourglass, ToggleRight,
} from "lucide-react";

const ICON_MAP = {
  trophy: Trophy,
  shield: Shield,
  "piggy-bank": PiggyBank,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  zap: Zap,
  crosshair: Crosshair,
  smartphone: Smartphone,
  handshake: Handshake,
  "dollar-sign": DollarSign,
  microscope: Microscope,
  monitor: Monitor,
  "bar-chart-3": BarChart3,
  "clipboard-list": ClipboardList,
  "message-circle": MessageCircle,
  "pen-tool": PenTool,
  "refresh-cw": RefreshCw,
  search: Search,
  ban: Ban,
  lightbulb: Lightbulb,
  "alert-triangle": AlertTriangle,
  laptop: Laptop,
  "book-open": BookOpen,
  globe: Globe,
  rocket: Rocket,
  briefcase: Briefcase,
  scale: Scale,
  sun: Sun,
  waves: Waves,
  compass: Compass,
  brain: Brain,
  "gamepad-2": Gamepad2,
  star: Star,
  lock: Lock,
  "key-round": KeyRound,
  mail: Mail,
  landmark: Landmark,
  bitcoin: Bitcoin,
  banknote: Banknote,
  "file-text": FileText,
  sprout: Sprout,
  wallet: Wallet,
  gift: Gift,
  "party-popper": PartyPopper,
  wrench: Wrench,
  phone: Phone,
  "graduation-cap": GraduationCap,
  "credit-card": CreditCard,
  circle: Circle,
  "building-2": Building2,
  package: Package,
  "dice-6": Dice6,
  award: Award,
  dog: Dog,
  droplets: Droplets,
  coins: Coins,
  "palm-tree": Palmtree,
  satellite: Satellite,
  settings: Settings,
  factory: Factory,
  gauge: Gauge,
  flame: Flame,
  infinity: Infinity,
  gem: Gem,
  "arrow-right": ArrowRight,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  check: Check,
  x: X,
  menu: Menu,
  "help-circle": HelpCircle,
  "external-link": ExternalLink,
  "circle-check": CircleCheck,
  "circle-x": CircleX,
  calendar: Calendar,
  newspaper: Newspaper,
  bot: Bot,
  "monitor-smartphone": MonitorSmartphone,
  shuffle: Shuffle,
  "folder-open": FolderOpen,
  "arrow-right-left": ArrowRightLeft,
  "map-pin": MapPin,
  "fast-forward": FastForward,
  "check-circle": CheckCircle2,
  hash: Hash,
  users: Users,
  timer: Timer,
  linkedin: Linkedin,
  // New icons for ranking system
  "chart-candlestick": ChartCandlestick,
  "chart-line": ChartLine,
  "chart-area": ChartArea,
  "chart-bar": ChartBar,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "shield-check": ShieldCheck,
  "shield-alert": ShieldAlert,
  "badge-check": BadgeCheck,
  "badge-percent": BadgePercent,
  "badge-dollar-sign": BadgeDollarSign,
  "circle-dollar-sign": CircleDollarSign,
  "circle-off": CircleOff,
  "hand-coins": HandCoins,
  vault: Vault,
  crown: Crown,
  sparkles: Sparkles,
  copy: Copy,
  signal: Signal,
  server: Server,
  layers: Layers,
  "grid-3x3": Grid3x3,
  target: Target,
  activity: Activity,
  cpu: Cpu,
  code: Code,
  apple: Apple,
  moon: Moon,
  umbrella: Umbrella,
  headphones: Headphones,
  "scan-line": ScanLine,
  receipt: Receipt,
  fuel: Fuel,
  wheat: Wheat,
  hourglass: Hourglass,
  "toggle-right": ToggleRight,
};

// Legacy EMOJI_MAP — kept for backward compatibility with any remaining emoji references
const EMOJI_MAP = {
  "\u{1F3C6}": "trophy",
  "\u{1F6E1}\uFE0F": "shield",
  "\u{1F4B0}": "piggy-bank",
  "\u{1F4C8}": "trending-up",
  "\u{1F4C9}": "trending-down",
  "\u26A1": "zap",
  "\u{1F3AF}": "crosshair",
  "\u{1F4F1}": "smartphone",
  "\u{1F91D}": "handshake",
  "\u{1F4B2}": "dollar-sign",
  "\u{1F52C}": "microscope",
  "\u{1F5A5}\uFE0F": "monitor",
  "\u{1F4CA}": "bar-chart-3",
  "\u{1F4CB}": "clipboard-list",
  "\u{1F4AC}": "message-circle",
  "\u270D\uFE0F": "pen-tool",
  "\u{1F504}": "refresh-cw",
  "\u{1F50D}": "search",
  "\u{1F6AB}": "ban",
  "\u{1F4A1}": "lightbulb",
  "\u26A0\uFE0F": "alert-triangle",
  "\u{1F4BB}": "laptop",
  "\u{1F4DA}": "book-open",
  "\u{1F4D6}": "book-open",
  "\u{1F30D}": "globe",
  "\u{1F680}": "rocket",
  "\u{1F454}": "briefcase",
  "\u2696\uFE0F": "scale",
  "\u2600\uFE0F": "sun",
  "\u{1F30A}": "waves",
  "\u{1F9ED}": "compass",
  "\u{1F9E0}": "brain",
  "\u{1F3AE}": "gamepad-2",
  "\u2B50": "star",
  "\u{1F512}": "lock",
  "\u{1F510}": "key-round",
  "\u{1F4BC}": "briefcase",
  "\u{1F4E7}": "mail",
  "\u{1F3E6}": "landmark",
  "\u2622\uFE0F": "landmark",
  "\u20BF": "bitcoin",
  "\u{1F4B5}": "banknote",
  "\u{1F4C4}": "file-text",
  "\u{1F331}": "sprout",
  "\u{1F4B8}": "wallet",
  "\u{1F381}": "gift",
  "\u{1F386}": "gift",
  "\u{1F389}": "party-popper",
  "\u{1F527}": "wrench",
  "\u{1F4DE}": "phone",
  "\u{1F393}": "graduation-cap",
  "\u{1F4B3}": "credit-card",
  "\u{1F7E2}": "circle",
  "\u{1F3E2}": "building-2",
  "\u{1F4E6}": "package",
  "\u{1F3B0}": "dice-6",
  "\u{1F947}": "award",
  "\u{1F436}": "dog",
  "\u{1F4A7}": "droplets",
  "\u{1FA99}": "coins",
  "\u{1F334}": "palm-tree",
  "\u{1F4E1}": "satellite",
  "\u2699\uFE0F": "settings",
  "\u{1F3ED}": "factory",
  "\u{1F4AF}": "gauge",
  "\u{1F4AA}": "gauge",
  "\u{1F525}": "flame",
  "\u{1F4A5}": "zap",
  "\u267E\uFE0F": "infinity",
  "\u{1F517}": "external-link",
  "\u2753": "help-circle",
  "\u{1F4F0}": "newspaper",
  "\u{1F916}": "bot",
  "\u{1F5D2}\uFE0F": "calendar",
  "\u{1F4C5}": "calendar",
  "\u{1F500}": "shuffle",
  "\u{1F4C2}": "folder-open",
  "\u{1F4B1}": "arrow-right-left",
  "\u{1F4CD}": "map-pin",
  "\u23E9": "fast-forward",
  "\u2714\uFE0F": "check-circle",
  "\u2705": "circle-check",
  "\u26D4": "ban",
  "0\uFE0F\u20E3": "hash",
  "\u27A1\uFE0F": "arrow-right",
  "\u{1F9D1}\u200D\u{1F4BC}": "users",
  "\u{1F4DC}": "file-text",
  "\u262A\uFE0F": "landmark",
  "\u{1F465}": "users",
  "\u{1F48E}": "gem",
};

export default function Icon({ name, size = 18, color, strokeWidth = 2, style = {}, className }) {
  if (!name) return null;

  // Check EMOJI_MAP first (legacy support)
  const mapped = EMOJI_MAP[name];
  const iconName = mapped || name;

  const Component = ICON_MAP[iconName];
  if (Component) {
    return <Component size={size} color={color} strokeWidth={strokeWidth} style={style} className={className} />;
  }

  // Fallback: render string as-is (for flags, unknown emojis)
  return <span style={{ fontSize: size, lineHeight: 1, ...style }} className={className}>{name}</span>;
}

export function IconBox({ name, color, size = 28, iconSize = 14 }) {
  return (
    <span style={{
      width: size, height: size, borderRadius: 6,
      background: `${color}15`,
      display: "inline-flex", alignItems: "center", justifyContent: "center",
      flexShrink: 0,
    }}>
      <Icon name={name} size={iconSize} color={color} />
    </span>
  );
}

// Re-export commonly used icons for direct import
export {
  ArrowRight, ChevronRight, ChevronDown, ChevronUp,
  Check, X, Menu, HelpCircle, ExternalLink,
  CircleCheck, CircleX,
};
